const express=require('express');
const app=express();
const mongoose=require("mongoose");



main().then(()=>{
    console.log("connection ok");
})
.catch(err => console.log(err));
async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/buy');
}
const firstSchema=new mongoose.Schema({
    name:String,
    quantity:String,
    image:String,
    price:Number
})

const First=mongoose.model("First",firstSchema);
let by=[
    {
        name:"batti",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328396/ph33_inzem9.png",
        price:10,
    },
    {
        name:"chocolate",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328393/ph29_ixeejg.png",
        price:5,
    },
    {
        name:"surf-excel",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328389/ph16_gwjbqv.png",
        price:10,
    },
    {
        name:"mangaldeep",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328387/ph9_l2oabv.png",
        price:10,
    },
    {
        name:"colgate",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328384/ph12_bv8ole.png",
        price:20,
    },
    {
        name:"lifebuoy",
        quanti:"4",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328383/ph8_ninhsw.png",
        price:36,
    },
    {
        name:"natkhat-blue",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328381/ph3_wejhun.png",
        price:10,
    },
    {
        name:"crax",
        quantity:"10",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328380/ph2_zex29b.png",
        price:10,
    },
    {
        name:"amla",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328375/ph5_kj9foz.png",
        price:20,
    },
    {
        name:"amla",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328376/ph6_vc90os.png",
        price:10,
    },
    {
        name:"lux",
        quantity:"4",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328372/ph7_l8awct.png",
        price:36,
    },
    {
        name:"natkhat",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328372/ph1_nyoeg1.png",
        price:10,
    },
    {
        name:"washing-powder",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328397/ph117_rk2znf.png",
        price:60,
    },
    {
        name:"moong-Dal",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328396/ph36_ipkll2.png",
        price:10,
    },
    {
        name:"tiranga",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328396/ph32_jfeaew.png",
        price:10,
    },
    {
        name:"crax-pipe",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328396/ph35_zpqzjd.png",
        price:10,
    },
    {
        name:"lollypop",
        quantity:"5",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328395/ph31_fn1c9t.png",
        price:10,
    },
    {
        name:"moms-magic",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328394/ph28_gfpb3b.png",
        price:10,
    },
    {
        name:"namak",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328394/ph34_gpbx2d.png",
        price:10,
    },
    {
        name:"jhabha",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328393/ph26_p96i6c.png",
        price:10,
    },
    {
        name:"rado",
        quantity:"6",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328393/ph19_s1isxr.png",
        price:55,
    },
    {
        name:"clinic-plus",
        quantity:"5",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328392/ph23_iseae8.png",
        price:5,
    },
    {
        name:"tongue-cleaner",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328392/ph27_aa6ufy.png",
        price:10,
    },
    {
        name:"vidisha",
        quantity:"6",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328392/ph21_gqierm.png",
        price:55,
    },
    {
        name:"rado",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328392/ph18_bk7lbi.png",
        price:55,
    },
    {
        name:"match-box",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328391/ph25_fz9wnu.png",
        price:10,
    },
    {
        name:"tea-cl",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328390/ph22_qfrrfa.png",
        price:20,
    },
    {
        name:"deepak",
        quantity:"12",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328391/ph24_nkjyxc.png",
        price:24,
    },
    {
        name:"vidisha",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328390/ph20_zdcm4k.png",
        price:10,
    },
    {
        name:"pen",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328389/ph15_o2ztdp.png",
        price:5,
    },
    {
        name:"handwash",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328389/ph17_tnl3lg.png",
        price:100,
    },
    {
        name:"clasic-tea",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328387/ph10_hr4hfi.png",
        price:75,
    },
    {
        name:"brush",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729328387/ph13_omcofw.png",
        price:20,
    },
    {
        name:"lighter",
        quantity:"1",
        image:"https://res.cloudinary.com/dnpo4lrgl/image/upload/v1729340409/IMG20241018141340_vsddwg.jpg",
        price:10,
    }
    
];
First.insertMany(by);

app.listen(8080,()=>{
    console.log("server start on 8080");
})